apiVersion: v1
kind: ConfigMap
metadata:
  name: springboot-config
data:
  application.yml: |
    welcome:
      message: Welcome to SpringBoot on KubernetesV2!
    server:
      shutdown: graceful
    spring:
      lifecycle:
        timeout-per-shutdown-phase: 20s