apiVersion: v1
kind: Service
metadata:
  name: springboot-service
  labels:
    app: springboot
spec:
  type: ClusterIP
  selector:
    app: springboot
  ports:
    - port: 8080
      targetPort: 8080