apiVersion: skaffold/v2beta8
kind: Config
metadata:
  name: springboot-service
build:
  artifacts:
  - image: sagiransari/springboot-k8s
    buildpacks:
      builder: gcr.io/paketo-buildpacks/builder:base-platform-api-0.3
      env:
        - BP_JVM_VERSION=11.*
      dependencies:
        paths:
          - src

deploy:
  kubectl:
    manifests:
      - k8s/*
