spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mydb
  r2dbc:
    url: r2dbcs:mysql://localhost:3306/test
    username: root
    password: password
    pool:
      initial-size: 10
      max-size: 30
      max-idle-time: 15s
      validation-query: SELECT 1
server:
  port: 8081
